apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      annotations:
            argocd.argoproj.io/ignore-resource-updates: "true"
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ghcr.io/kyverno/test-verify-image:signed
        ports:
        - containerPort: 80

